version: '3'

services:
  app:
    build:
      context: .
      dockerfile: kubernetes/Dockerfile
    image: chronohancer-app
    container_name: chronohancer-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - mysql
      - redis
    networks:
      - chronohancer
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=chronohancer
      - DB_USERNAME=chronohancer
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis

  nginx:
    image: nginx:alpine
    container_name: chronohancer-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./kubernetes/nginx-config.yaml:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - chronohancer

  mysql:
    image: mysql:8.0
    container_name: chronohancer-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=chronohancer
      - MYSQL_USER=chronohancer
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - SERVICE_NAME=mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chronohancer

  redis:
    image: redis:alpine
    container_name: chronohancer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - chronohancer

networks:
  chronohancer:
    driver: bridge

volumes:
  mysql-data:
    driver: local