apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronohancer.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "chronohancer.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.app.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}