{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chronohancer.fullname" . }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "chronohancer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "chronohancer.app.fullname" . }}
            port:
              number: 80
{{- end }}