apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronohancer.fullname" . }}-nginx-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "chronohancer.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name {{ .Values.nginx.config.serverName }};
        root /var/www/html/public;
        index index.php;

        client_max_body_size {{ .Values.nginx.config.clientMaxBodySize }};

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }