apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chronohancer.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "chronohancer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.app.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}