apiVersion: v1
kind: ConfigMap
metadata:
  name: chronohancer-config
  namespace: chronohancer
data:
  APP_NAME: "Chronohancer"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://chronohancer.example.com"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "info"
  DB_CONNECTION: "mysql"
  DB_HOST: "chronohancer-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "chronohancer"
  DB_USERNAME: "chronohancer"
  CACHE_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  REDIS_HOST: "chronohancer-redis"
  REDIS_PORT: "6379"