apiVersion: v2
name: chronohancer
description: A Helm chart for Chronohancer Laravel application
type: application
version: 0.0.8
appVersion: "0.0.8"
keywords:
  - laravel
  - php
  - web
  - mysql
  - redis
maintainers:
  - name: Chronohancer Team