# Default values for chronohancer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Global settings
global:
  # Domain name for the application
  domain: chronohancer.example.com
  # Environment settings
  env: production
  # TLS settings
  tls:
    enabled: true
    secretName: chronohancer-tls

# Namespace configuration
namespace:
  create: true
  name: chronohancer

# Application configuration
app:
  replicaCount: 2
  image:
    repository: chronohancer
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  config:
    APP_NAME: "Chronohancer"
    APP_ENV: "production"
    APP_DEBUG: "false"
    APP_URL: "http://chronohancer.example.com"
    LOG_CHANNEL: "stack"
    LOG_LEVEL: "info"
    DB_CONNECTION: "mysql"
    DB_HOST: "chronohancer-mysql"
    DB_PORT: "3306"
    DB_DATABASE: "chronohancer"
    DB_USERNAME: "chronohancer"
    CACHE_DRIVER: "redis"
    QUEUE_CONNECTION: "redis"
    SESSION_DRIVER: "redis"
    REDIS_HOST: "chronohancer-redis"
    REDIS_PORT: "6379"
  secret:
    # These should be base64 encoded in production
    APP_KEY: "base64_encoded_app_key"
    DB_PASSWORD: "base64_encoded_db_password"
    REDIS_PASSWORD: "base64_encoded_redis_password"
  storage:
    size: 10Gi
    storageClass: standard

# Nginx configuration
nginx:
  image:
    repository: nginx
    tag: 1.25
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  config:
    serverName: "_"
    clientMaxBodySize: "100m"

# MySQL configuration
mysql:
  enabled: true
  image:
    repository: mysql
    tag: 8.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  storage:
    size: 10Gi
    storageClass: standard

# Redis configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: 7.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  storage:
    size: 5Gi
    storageClass: standard

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"