name: Build and Push Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for nginx
        id: meta-nginx
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/nginx
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=sha,format=short

      - name: Extract metadata for php-fpm
        id: meta-php-fpm
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/php-fpm
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=sha,format=short

      # Build the base PHP image first (but don't push)
      - name: Build php-fpm base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/common/php-fpm/Dockerfile
          target: builder
          load: true
          tags: php-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Push the final PHP-FPM image
      - name: Build and push php-fpm image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/common/php-fpm/Dockerfile
          target: production
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-php-fpm.outputs.tags }}
          labels: ${{ steps.meta-php-fpm.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Use builder stage to build frontend assets that will have vendor dependencies
      - name: Create temp container from builder
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/common/php-fpm/Dockerfile
          target: builder
          outputs: type=local,dest=./build-output

      # Build and push Nginx image with frontend assets
      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/nginx/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VENDOR_DIR=./build-output/var/www/vendor
